CREATE TABLE booklist (
 id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 book_name TEXT NOT NULL,
 book_category TEXT NOT NULL,
 book_desc TEXT NOT NULL,
 cover_img_filename TEXT NOT NULL,
 cover_img_alt TEXT NOT NULL
 isbn_num TEXT NOT NULL
);